project_management/app/urls.py
from django.contrib import admin
from django.urls import path
from app.views import home , login , signup , add_todo , signout , delete_todo, change_todo,about,contact


urlpatterns = [
   path('' , home , name='home' ), 
   path('login/' ,login  , name='login'), 
   path('signup/' , signup ), 
   path('add-todo/' , add_todo ), 
   path('delete-todo/<int:id>' , delete_todo ), 
   path('change-status/<int:id>/<str:status>' , change_todo ), 
   path('logout/' , signout ), 
   path('about/', about),
   path('contact/', contact),
]

project_management/project_management/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('app.urls'))
]

project_management/app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
#  title 
#  status
#  date - current 
#  user 
#  priority


class TODO(models.Model):
    status_choices = [
    ('C', 'COMPLETED'),
    ('P', 'PENDING'),
    ]
    members_choices = [
    ('1', '1️⃣'),
    ('2', '2️⃣'),
    ('3', '3️⃣'),
    ('4', '4️⃣'),
    ('5', '5️⃣'),
    ('6', '6️⃣'),
    ('7', '7️⃣'),
    ('8', '8️⃣'),
    ('9', '9️⃣'),
    ('10', '🔟'),
    ]
    title = models.CharField(max_length=50)
    status = models.CharField(max_length=2 , choices=status_choices)
    user  = models.ForeignKey(User  , on_delete= models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    members = models.CharField(max_length=2 , choices=members_choices)
    ldate = models.DateField(null=True,blank=True)


class Contact(models.Model):
    cname = models.CharField(max_length=30,blank=True,null=True)
    text = models.CharField(max_length=250,blank=True,null=True)

project_management/app/forms.py
from django.forms import ModelForm

from app.models import TODO
class TODOForm(ModelForm):
    class Meta:
        model = TODO
        fields = ['title' , 'status' , 'members', 'ldate']

project_management/app/views.py
from django.shortcuts import render , redirect
from django.http import HttpResponse
from django.contrib.auth import authenticate , login as loginUser , logout
from django.contrib.auth.forms import UserCreationForm , AuthenticationForm
# Create your views here.
from app.forms import TODOForm
from app.models import TODO, Contact
from django.contrib import messages
from django.contrib.auth.decorators import login_required


@login_required(login_url='login')
def home(request):
    if request.user.is_authenticated:
        user = request.user
        form = TODOForm()
        todos = TODO.objects.filter(user = user).order_by('members')
        return render(request , 'index.html' , context={'form' : form , 'todos' : todos, 'user': user})

def login(request):
    if request.method == 'GET':
        form1 = AuthenticationForm()
        context = {
            "form" : form1
        }
        return render(request , 'login.html' , context=context )
    else:
        form = AuthenticationForm(data=request.POST)
        print(form.is_valid())
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username = username , password = password)
            if user is not None:
                loginUser(request , user)
                return redirect('home')
        else:
            context = {
                "form" : form
            }
            return render(request , 'login.html' , context=context )


def signup(request):

    if request.method == 'GET':
        form = UserCreationForm()
        context = {
            "form" : form
        }
        return render(request , 'signup.html' , context=context)
    else:
        print(request.POST)
        form = UserCreationForm(request.POST)  
        context = {
            "form" : form or None
        }
        if form.is_valid():
            user = form.save()
            print(user)
            if user is not None:
                messages.success(request, "Account created Successfully" )
                return redirect('login')
        else:
            return render(request , 'signup.html' , context=context)



@login_required(login_url='login')
def add_todo(request):
    if request.user.is_authenticated:
        user = request.user
        print(user)
        form = TODOForm(request.POST)
        if form.is_valid():
            print(form.cleaned_data)
            todo = form.save(commit=False)
            todo.user = user
            todo.save()
            print(todo)
            messages.success(request, "Task added Successfully" )
            return redirect("home")
        else: 
            return render(request , 'index.html' , context={'form' : form})


def delete_todo(request , id ):
    print(id)
    TODO.objects.get(pk = id).delete()
    messages.success(request, "Task deleted Successfully" )
    return redirect('home')

def change_todo(request , id  , status):
    todo = TODO.objects.get(pk = id)
    todo.status = status
    todo.save()
    return redirect('home')


def signout(request):
    logout(request)
    return redirect('login')


def about(request):
    return render(request, "about.html")

def contact(request):
    if request.method == 'GET':
        if request.user.is_authenticated:
            cname = request.POST.get('cname')
            text = request.POST.get('text')
            ins = Contact(cname = cname, text = text)
            ins.save()
            messages.success(request, 'Your Response Submitted Successfully')
            return render(request, "contact.html")
        else:
            messages.error(request,'Please login before contact!')
            return render(request, "login.html")
    return render(request, 'contact.html')

project_management/app/templates/about.html
 {% extends 'base.html' %}
 {% block title %} About: Meetrack{% endblock title %}
 {% block aboutActive %} active{% endblock aboutActive %}
 {% load static %}
{% block content %}
        <style>
            .container{
                margin-top: 30px;
                box-shadow: 5px 5px 5px 5px grey;
                height: 90vh;
                padding: 20px;
                background-color: antiquewhite;
            }
            .card{
                padding: 10px;
                border-radius: 20px;
            }
            .card a{
                border: 2px solid black;
                border-radius: 10px;
                background-color: cornflowerblue;
                padding: 8px 15px;
                color: white;
                text-align: center;
                box-shadow: 5px 5px 5px 5px grey;
            }
            .card a:hover{
                background-color: burlywood;
                color: black;
            }
        </style>

<body>
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <div class="card" style="width: 18rem;">
                    <img src= "{% static 'images/181500332.jpg' %}" class="card-img-top" alt="..." width="200px" height="230px">
                    <div class="card-body my-0">
                        <h5 class="card-title">
                            Krishna Kant Sharma
                        </h5>
                        <p> <span style="font-weight: 600; text-decoration: underline;">Software Engineer Trainee at Devslane</span> <br> Roll number : 181500332 <br> Batch: 2022 <br>Computer Science(IOT)</p>
                        <a href="https://github.com/krishnasharma5547" alt="" target="_blank">Github</a>
                    </div>
                    
                </div>
            </div>

            <div class="col-md-4">
                <div class="card" style="width: 18rem;">
                    <img src= "{% static 'images/181500515.jpg' %}" class="card-img-top" alt="..." width="200px" height="230px">
                    <div class="card-body">
                        <h5 class="card-title">Priyanshu Shukla</h5>
                        <p>Roll number : 181500515 <br> Batch: 2022</p>
                        <p class="card-text">Computer Science</p>
                    </div>
                    <div class="card-body">
                        <a href="https://github.com/priyanshu3666" class="card-link" target="_blank">Github</a>
                        
                    </div>
                </div>

            </div>
            <div class="col-md-4">
                <div class="card" style="width: 18rem;">
                   <img src= "{% static 'images/181500061.jpg' %}" class="card-img-top" alt="..." width="200px" height="230px">
                    <div class="card-body">
                        <h5 class="card-title">Akashi Gupta</h5>
                        <p>Roll number : 181500061 <br> Batch: 2022</p>
                        <p class="card-text">Computer Science(IOT)</p>
                    </div>
                    <div class="card-body">
                        <a href="https://github.com/akashi-gupta" class="card-link" target="_blank">Github</a>
                        
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

project_management/app/templates/base.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <title>{% block title %}{% endblock title %}</title>
</head>

<body>
    <!-- navabar start -->
    <nav class="navbar navbar-expand-lg  navbar-dark bg-dark">
        <a class="navbar-brand" href="/">Meetrack</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                {% csrf_token %}

                 {% if request.user.is_authenticated %}
                <li class="nav-item" style="color:white !important">
                    <a class="navbar-brand" href="#">Welcome {{user}}</a>
                </li>
                {% endif%}
                {% if request.user.is_authenticated %}
                <li class="nav-item {% block logoutActive %} {% endblock logoutActive %}">
                    <a class="nav-link" href="/logout">Logout</a>
                </li>

                {% else %}
                <li class="nav-item {% block loginActive %} {% endblock loginActive %}">
                    <a class="nav-link" href="/login">Login</a>
                </li>
                <li class="nav-item {% block signupActive %} {% endblock signupActive %}">
                    <a class="nav-link" href="/signup">Signup</a>
                </li>
                <li>
                <a class=""
                </li>
                {% endif %}
                
                <li class="nav-item {% block aboutActive %} {% endblock aboutActive %}">
                    <a class="nav-link" href="/about">About Us</a>
                </li>

                <li class="nav-item {% block contactActive %} {% endblock contactActive %}">
                    <a class="nav-link" href="/contact">Contact Us</a>
                </li>
            </ul>
        </div>
    </nav>
    <!-- changing coontent -->
    <div>
        {% block content %}

        {% endblock %}
    </div>
    <!-- end -->

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
        crossorigin="anonymous"></script>
</body>

</html>

project_management/app/templates/contact.html
{% extends 'base.html' %}
{% block title %} Contact: Meetrack {% endblock title %}
{% block contactActive %} active{% endblock contactActive %}
{% load static %}
{% block content %}


<style>
    body {
        background-image: url("{% static 'images/background.jpg' %}");
        background-position: top 50px;
        background-attachment: fixed;
        background-repeat: no-repeat;
        background-size: cover;
    }

    .contact_form {
        margin-top: 20px;
        padding: 20px;
        background-color: rgb(223, 228, 241);
        border: 2px solid black;
        border-radius: 20px;
        box-shadow: 5px 5px 5px 5px rgb(116, 119, 119);
    }
    .card-body a{
        padding: 10px 20px;
        background-color: aquamarine;
        border-radius: 10px;
        margin-top: 5px;

    }
    .card{
        box-shadow: 5px 5px 5px 5px rgb(116, 119, 119);

    }

    .card-body a:hover{
        background-color: cornflowerblue;
        text-decoration: none;
        color: white;
    }
</style>

{% for message in messages %}
<div class="container-fluid p-0">
  <div class="alert {{ message.tags }} alert-dismissible" role="alert" >
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
  </div>
</div>
{% endfor %}

<div class="container">
    <div class="row">
        <div class="col-md-5">

        </div>
        <div class="col-md-7 ">
            <div class="contact_form">
                {% csrf_token %}
                <form action="/contact/" method="get">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="contact_name" class="form-label">Name: </label>
                        <input type="text" class="form-control" id="contact_name" placeholder="Enter your name">
                    </div>
                    <div class="mb-3">
                        <label for="text" class="form-label">Write Something For us</label>
                        <textarea class="form-control" id="text" rows="4"></textarea>
                    </div>
                    <button type="submit" class="btn btn-success">Submit</button>
                </form>
            </div>
            <div class="card w-100 mt-4">
                <div class="card-body">
                    <h5 class="card-title" target="_blank">Contact US</h5>
                    <p class="card-text" target="_blank">contact details</p>
                    <a href="tel:8445080110" target="_blank">Call US</a>
                    <a href="callto:8445080110" target="_blank">Skype Call</a>
                    <a href = "mailto: kksharmaz786@gmail.com" target="_blank">Send Mail</a>
                    <a href="https://www.facebook.com/profile.php?id=100008457829281" target="_blank">Facebook</a>
                    <a href="https://twitter.com/krishna38748795" target="_blank">Tweet</a>
                </div>
            </div>
        </div>
    </div>
</div>


    {% endblock %}

project_management/app/templates/index.html
{% extends 'base.html' %}
 {% block title %} Meetrack {% endblock title %}
{% block content %}

<style>
  body{
    background-color: rgb(147, 155, 150);
  }
  .task{
    background-color: rgb(97, 206, 206);
    color: white;
    font-weight: 700;
  }
  #id_title{
    width:160px;
    margin-left:12%;
  }
  #id_status{
width:160px;
margin-left:8%;
  }
  #id_members{
width:160px;
margin-left:1%
  }
  #id_ldate{
width:160px;
margin-left:2rem;
  }
</style>

{% for message in messages %}
<div class="container-fluid p-0">
  <div class="alert {{ message.tags }} alert-dismissible" role="alert" >
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
  </div>
</div>
{% endfor %}

<div>
  <div class="container pt-4">
    <div class="row  p-0 mt-4">
      <div class="col-lg-4 mx-auto shadow p-0 task">
        <div class="alert alert-info">
          <h2>Add New Task</h2>
        </div>
        <div class="p-4 ">
          <form action="/add-todo/" method="POST">
            {% csrf_token %}
            {{form.as_p}}
            <hr>
            <input type="submit" value="ADD" class="btn btn-info">
          </form>
        </div>
      </div>


<br>



<div class="modal" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Modal title</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <p>Modal body text goes here.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>


      <div class="col">
        <div class="border">

          {% if todos|length == 0 %}

          <div class="p-4">
            <br>
            <br>
            <div class="alert alert-info text-center">
              <p class="" style="font-size: 30px;">No Tasks</p>
            </div>
            <br>
            <br>
          </div>

          {%else%}
          <div>
            <table class="table table-striped  table-dark table-hover">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Title</th>
                  <th>Status</th>
                  <th>Members</th>
                  <th>Action</th>
                  <th>Last Date</th>
                </tr>
              </thead>

              <tbody>

                {% for todo in todos %}
                <tr>
                  <td>{{forloop.counter}}</td>
                  <td>{{todo.title}}</td>
                  <td>
                    {% if todo.status == 'C'%}
                    ✅
                    {%else%}
                    🕒
                    {%endif%}
                  </td>
                  <td>{{todo.members}}</td>
                  <td>
                    <a href="/delete-todo/{{todo.id}}" title="Delete" class="">🗑️</a>
                    {% if todo.status == 'P'%}
                    <a href="/change-status/{{todo.id}}/C" title="Mark Completed" class="">✅</a>
                    {%else%}
                    <a href="/change-status/{{todo.id}}/P" title="Mark Pending" class="">🕒</a>
                    {%endif%}
                  </td>
                  <td>{{todo.ldate}}</td>
                </tr>
                {%endfor%}
              </tbody>
            </table>
          </div>
          {%endif%}

        </div>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
    document.getElementById('id_ldate').type = 'date';
</script>

{% endblock %}

project_management/app/templates/login.html
  {% extends 'base.html' %}
   {% block title %} Login: Meetrack {% endblock title %}
   {% block loginActive %} active{% endblock loginActive %}
  {% block content %}
  
  
<style>

  body{
    background-color:lightgray;
  }
  .col-lg-4{
    background-color:rgb(226, 164, 105);
    font-weight: 600;
    color: white !important;
  }
  #id_password{
    margin-left:11%;
  }

  input{
    margin-left:10%;
  }

  
  </style>
{% for message in messages %}
<div class="container-fluid p-0">
  <div class="alert {{ message.tags }} alert-dismissible" role="alert" >
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
  </div>
</div>
{% endfor %}

  <div class="container pt-4">
    <div class="col-lg-4 mx-auto shadow p-0 mt-4">
      <div class="alert alert-info">
        <h2>Login Here</h2>
      </div>
      <div class="p-4">
        <form action="/login/" method="POST">
          {% csrf_token %}
          {{form.as_p}}
          <hr>
          <input type="submit" value="Login" class="btn btn-info">
        </form>
      </div>
    </div>
  </div>
  {% endblock %}


  

project_management/app/templates/signup.html
   {% extends 'base.html' %}
    {% block title %} Signup: Meetrack {% endblock title %}
    {% block signupActive %} active{% endblock signupActive %}
    {% load static %}
{% block content %}

<style>

  {% comment %} body{
    background-color:rgb(78, 121, 122)
  } {% endcomment %}
  body {
        background-image: url("{% static 'images/px.jpg' %}");
        background-position: top 50px;
        background-attachment: fixed;
        background-repeat: no-repeat;
        background-size: cover;
    }
  .helptext{
    visibility: hidden;
    display:none;
  }
  .col-lg-5{
    background-color:transparent;
    font-weight: 600;
    color: white !important;
    box-shadow:5px 5px 5px 5px white;
  }
  .p-4{
    opacity:0.7;
  }
  .shadow-box{
    box-shadow:5px 5px 5px 5px rgb(185, 174, 174);
  }
  
  form ul li{
    display:none;
  }
  #id_password1{
    margin-left:120px;
  }
  #id_password2{
    margin-left:22px;
  }
  #id_username{
    margin-left:116px;
  }
  
  </style>



{% if form.errors %}
<div class="alert alert-danger alert-dismissible col-12 mx-1" role="alert">
    <div id="form_errors">
        {% for key, value in form.errors.items %}
            <span class="fieldWrapper">
                {{ key }}:{{ value }}
            </span>
        {% endfor %}
    </div>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
{% endif %}

<div class="containter pt-4">
  <div class="col-lg-5 shadow-box  mx-auto p-0">
    <div class="alert alert-success">
      <h2>Create Account</h2>
    </div>
    <div class="p-4">
      <form method="post" action="/signup/" >
        {% csrf_token %}
        {{ form.as_p }}
        <hr>
        <input class="btn btn-success" type="submit" value="Create Account">
      </form>
    </div>
  </div>
</div>

{% endblock %}